"""Readable Chinese term dictionaries used as the primary source of truth."""

from __future__ import annotations

from typing import Dict


READABLE_PAYMENT_INSTITUTION_TERMS: Dict[str, str] = {
    "支付宝": "Alipay",
    "支付宝（中国）网络技术有限公司": "Alipay (China) Network Technology Co Ltd",
    "支付宝(中国)网络技术有限公司": "Alipay (China) Network Technology Co Ltd",
    "财付通": "Tenpay",
    "财付通支付科技有限公司": "Tenpay Payment Technology Co Ltd",
    "深圳市财付通支付科技有限公司": "Shenzhen Tenpay Payment Technology Co Ltd",
    "微信支付": "WeChat Pay",
    "微信支付商户平台": "WeChat Pay Merchant Platform",
    "网银在线": "NetBank Online",
    "网银在线（北京）科技有限公司": "NetBank Online (Beijing) Technology Co Ltd",
    "网银在线(北京)科技有限公司": "NetBank Online (Beijing) Technology Co Ltd",
    "京东支付": "JD Pay",
    "京东钱包": "JD Wallet",
    "银联": "UnionPay",
    "中国银联": "China UnionPay",
    "云闪付": "UnionPay QuickPass",
    "银联云闪付": "UnionPay QuickPass",
    "京东闪付": "JD QuickPass",
    "白条闪付": "Baitiao QuickPass",
    "拉卡拉": "Lakala",
    "拉卡拉支付股份有限公司": "Lakala Payment Corporation",
}


READABLE_PAYMENT_CHANNEL_TERMS: Dict[str, str] = {
    "扫码": "Scan to Pay",
    "扫码支付": "Scan Payment",
    "扫码收款": "Scan Collection",
    "二维码收款": "QR Code Collection",
    "二维码付款": "QR Code Payment",
    "付款码支付": "Payment Code Payment",
    "条码支付": "Barcode Payment",
    "刷卡": "Card Swipe",
    "刷卡消费": "Card Consumption",
    "POS消费": "POS Purchase",
    "POS交易": "POS Transaction",
    "NFC支付": "NFC Payment",
    "闪付": "QuickPass",
    "刷脸支付": "Face Payment",
    "无感支付": "Seamless Payment",
    "小程序支付": "Mini Program Payment",
    "公众号支付": "Official Account Payment",
    "H5支付": "H5 Payment",
    "APP支付": "App Payment",
    "网关支付": "Gateway Payment",
    "协议支付": "Agreement Payment",
    "免密支付": "Password-free Payment",
    "代扣签约": "Auto Debit Authorization",
    "商户扣款": "Merchant Debit",
}


READABLE_BANKING_GLOSSARY_TERMS: Dict[str, str] = {
    "交易明细": "Transaction Details",
    "历史明细": "Historical Statement",
    "历史明细（电子版）": "Historical Statement (Electronic Version)",
    "电子版": "Electronic Version",
    "电子回单": "Electronic Receipt",
    "交易日期": "Transaction Date",
    "交易时间": "Transaction Time",
    "摘要": "Description",
    "地区": "Region",
    "对方户名": "Counterparty Name",
    "对方账户": "Counterparty Account",
    "对方账号": "Counterparty Account",
    "余额": "Balance",
    "收入金额": "Income Amount",
    "支出金额": "Expenditure Amount",
    "本页收入合计": "Page Income Total",
    "本页支出合计": "Page Expenditure Total",
    "本页交易笔数": "Transactions on Page",
    "制表时间": "Generated At",
    "活期": "Demand Deposit",
    "定期": "Time Deposit",
    "存款": "Deposit",
    "取款": "Withdrawal",
    "现金存入": "Cash Deposit",
    "现金支取": "Cash Withdrawal",
    "电子银行": "Electronic Banking",
    "网上银行": "Internet Banking",
    "手机银行": "Mobile Banking",
    "自助终端": "Self-Service Terminal",
    "柜台": "Counter",
    "快捷支付": "Quick Payment",
    "无卡支付": "Cardless Payment",
    "扫码支付": "QR Code Payment",
    "转账": "Transfer",
    "转入": "Transfer In",
    "转出": "Transfer Out",
    "跨行转账": "Interbank Transfer",
    "汇入": "Incoming Remittance",
    "汇出": "Outgoing Remittance",
    "来账": "Incoming Transfer",
    "收款": "Collection",
    "付款": "Payment",
    "代扣": "Auto Debit",
    "代收": "Collection",
    "代发工资": "Payroll",
    "批量代发": "Bulk Payroll",
    "贷款": "Loan",
    "贷款还款": "Loan Repayment",
    "信用卡还款": "Credit Card Repayment",
    "结息": "Interest Settlement",
    "利息": "Interest",
    "收款人": "Payee",
    "电子结单": "e-Statement",
    "起止日期": "Date Range",
    "打印日期": "Print Date",
    "页码": "Page Number",
    "回单编号": "Receipt Number",
    "流水号": "Reference Number",
    "结算": "Settlement",
    "购汇": "FX Purchase",
    "汇率": "Exchange Rate",
    "授信额度": "Credit Line",
    "短信验证码": "SMS Verification Code",
    "双因素认证": "Two-Factor Authentication",
    "入账": "Posted",
    "出账": "Debited",
    "冲正": "Reversal",
    "冲销": "Write-off",
    "待入账": "Pending Posting",
    "手续费减免": "Service Fee Waiver",
    "本息转存": "Principal and Interest Rollover",
}
