"""Legacy compatibility terms for garbled banking text."""

from __future__ import annotations

from typing import Dict


BANKING_GLOSSARY_TERMS: Dict[str, str] = {
    "浜ゆ槗鏄庣粏": "Transaction Details",
    "鍘嗗彶鏄庣粏": "Historical Statement",
    "鍘嗗彶鏄庣粏锛堢數瀛愮増锛?": "Historical Statement (Electronic Version)",
    "鐢靛瓙鐗?": "Electronic Version",
    "鐢靛瓙鍥炲崟": "Electronic Receipt",
    "浜ゆ槗鏃ユ湡": "Transaction Date",
    "浜ゆ槗鏃堕棿": "Transaction Time",
    "浜ゆ槗鏈烘瀯": "Transaction Branch",
    "浜ゆ槗缃戠偣": "Transaction Outlet",
    "浜ゆ槗娓犻亾": "Transaction Channel",
    "浜ゆ槗闄勮█": "Transaction Remarks",
    "鎽樿": "Description",
    "澶囨敞": "Remarks",
    "闄勮█": "Remarks",
    "鍦板尯": "Region",
    "鎴峰悕": "Account Name",
    "鎴峰彿": "Account Number",
    "璐﹀彿": "Account Number",
    "鍗″彿": "Card Number",
    "閾惰鍗″彿": "Bank Card Number",
    "瀵规柟鎴峰悕": "Counterparty Name",
    "瀵规柟璐︽埛": "Counterparty Account",
    "瀵规柟璐﹀彿": "Counterparty Account",
    "瀵规柟寮€鎴疯": "Counterparty Bank",
    "浣欓": "Balance",
    "鍙敤浣欓": "Available Balance",
    "璐︽埛浣欓": "Account Balance",
    "浜ゆ槗閲戦": "Transaction Amount",
    "鏀跺叆閲戦": "Income Amount",
    "鏀嚭閲戦": "Expenditure Amount",
    "鏈〉鏀跺叆鍚堣": "Page Income Total",
    "鏈〉鏀嚭鍚堣": "Page Expenditure Total",
    "鏈〉浜ゆ槗绗旀暟": "Transactions on Page",
    "鍒惰〃鏃堕棿": "Generated At",
    "鍊熻鍗?": "Debit Card",
    "鍌ㄨ搫鍗?": "Savings Card",
    "鍊熻璐︽埛": "Debit Account",
    "娲绘湡": "Demand Deposit",
    "瀹氭湡": "Time Deposit",
    "閫氱煡瀛樻": "Call Deposit",
    "瀛樻": "Deposit",
    "鍙栨": "Withdrawal",
    "鐜伴噾瀛樺叆": "Cash Deposit",
    "鐜伴噾鏀彇": "Cash Withdrawal",
    "鐜伴噾鍙栨": "Cash Withdrawal",
    "寮€鎴疯": "Account Opening Bank",
    "寮€鎴风綉鐐?": "Account Opening Branch",
    "鐢靛瓙閾惰": "Electronic Banking",
    "缃戜笂閾惰": "Internet Banking",
    "鎵嬫満閾惰": "Mobile Banking",
    "鑷姪缁堢": "Self-Service Terminal",
    "鑷姪璁惧": "Self-Service Terminal",
    "鏌滈潰": "Counter",
    "鏌滃彴": "Counter",
    "ATM": "ATM",
    "ATM鏈?": "ATM",
    "蹇嵎鏀粯": "Quick Payment",
    "鏃犲崱鏀粯": "Cardless Payment",
    "鎵爜鏀粯": "QR Code Payment",
    "浜岀淮鐮佹敮浠?": "QR Code Payment",
    "閾惰仈蹇嵎": "UnionPay QuickPass",
    "鏀粯瀹?": "Alipay",
    "寰俊鏀粯": "WeChat Pay",
    "璐粯閫?": "Tenpay",
    "杞处": "Transfer",
    "杞叆": "Transfer In",
    "杞嚭": "Transfer Out",
    "鍚岃杞处": "Intra-bank Transfer",
    "璺ㄨ杞处": "Interbank Transfer",
    "姹囧叆": "Incoming Remittance",
    "姹囧嚭": "Outgoing Remittance",
    "鏉ヨ处": "Incoming Transfer",
    "鏀舵": "Collection",
    "浠樻": "Payment",
    "浠ｆ墸": "Auto Debit",
    "浠ｆ敹": "Collection",
    "浠ｅ彂宸ヨ祫": "Payroll",
    "鎵归噺浠ｅ彂": "Bulk Payroll",
    "璐锋": "Loan",
    "璐锋杩樻": "Loan Repayment",
    "淇＄敤鍗¤繕娆?": "Credit Card Repayment",
    "缁撴伅": "Interest Settlement",
    "鍒╂伅": "Interest",
    "鏀舵浜?": "Payee",
    "鐢靛瓙缁撳崟": "e-Statement",
    "鐢靛瓙鏈堢粨鍗?": "e-Statement",
    "蹇€熸敮浠樼郴缁?": "Faster Payment System",
    "杞暟蹇?": "FPS",
    "璧锋鏃ユ湡": "Date Range",
    "鎵撳嵃鏃ユ湡": "Print Date",
    "椤电爜": "Page Number",
    "鍥炲崟缂栧彿": "Receipt Number",
    "娴佹按鍙?": "Reference Number",
    "閾惰鍗?": "Bank Card",
    "淇＄敤鍗?": "Credit Card",
    "鍌ㄨ搫璐︽埛": "Savings Account",
    "缁撶畻璐︽埛": "Settlement Account",
    "鍩烘湰璐︽埛": "Basic Account",
    "涓€鑸处鎴?": "General Account",
    "璐︽埛绫诲瀷": "Account Type",
    "璐︽埛鐘舵€?": "Account Status",
    "鍗＄": "Card Type",
    "鍗＄墖鐘舵€?": "Card Status",
    "鎸傚け": "Loss Reporting",
    "琛ュ崱": "Card Replacement",
    "閿€鎴?": "Account Closure",
    "寮€鎴?": "Account Opening",
    "鎵嬬画璐?": "Service Fee",
    "璐︽埛绠＄悊璐?": "Account Management Fee",
    "骞磋垂": "Annual Fee",
    "鏈堣垂": "Monthly Fee",
    "宸ユ湰璐?": "Processing Fee",
    "鐭俊鏈嶅姟璐?": "SMS Service Fee",
    "婊炵撼閲?": "Late Fee",
    "杩濈害閲?": "Liquidated Damages",
    "鏈噾": "Principal",
    "鏈伅": "Principal and Interest",
    "璐锋鏈噾": "Loan Principal",
    "璐锋鍒╂伅": "Loan Interest",
    "閫炬湡": "Overdue",
    "閫炬湡杩樻": "Overdue Repayment",
    "鎻愬墠杩樻": "Early Repayment",
    "鎺堜俊棰濆害": "Credit Line",
    "淇＄敤棰濆害": "Credit Limit",
    "姹囩巼": "Exchange Rate",
    "璐眹": "FX Purchase",
    "缁撴眹": "FX Settlement",
    "鍞眹": "FX Sale",
    "澶栨眹": "Foreign Exchange",
    "澶栧竵": "Foreign Currency",
    "璺ㄥ姹囨": "Cross-border Remittance",
    "鍥介檯姹囨": "International Remittance",
    "澧冨唴姹囨": "Domestic Remittance",
    "鐜版眹": "Remittance",
    "鐜伴挒": "Cash",
    "鐭俊楠岃瘉鐮?": "SMS Verification Code",
    "鍔ㄦ€佸彛浠?": "One-Time Password",
    "涓€娆℃€у瘑鐮?": "One-Time Password",
    "鍙屽洜绱犺璇?": "Two-Factor Authentication",
    "瀹夊叏浠ょ墝": "Security Token",
    "鏁板瓧璇佷功": "Digital Certificate",
    "鏀跺崟": "Merchant Acquiring",
    "娓呯畻": "Clearing",
    "缁撶畻": "Settlement",
    "瀵硅处": "Reconciliation",
    "瀵硅处鍗?": "Statement",
    "鐢靛瓙瀵硅处鍗?": "Electronic Statement",
    "鍏ヨ处": "Posted",
    "鍑鸿处": "Debited",
    "鍊熸柟": "Debit",
    "璐锋柟": "Credit",
    "鍊熻": "Debit Entry",
    "璐疯": "Credit Entry",
    "鍊熻閲戦": "Debit Amount",
    "璐疯閲戦": "Credit Amount",
    "鏈閲戦": "Current Amount",
    "鍙戠敓棰?": "Transaction Amount",
    "鍏ヨ处閲戦": "Posted Amount",
    "鏀彇": "Withdrawal",
    "瀛樺叆": "Deposit",
    "鎵ｆ": "Debit",
    "鎵ｅ垝": "Direct Debit",
    "鍐叉": "Reversal",
    "鍐查攢": "Write-off",
    "鍐茶处": "Adjustment Reversal",
    "閫€姹?": "Returned Remittance",
    "閫€绁?": "Dishonored Bill",
    "閫€娆?": "Refund",
    "閫€璐?": "Fee Refund",
    "閫€绋?": "Tax Refund",
    "绋庤垂": "Taxes and Fees",
    "缂寸◣": "Tax Payment",
    "浠ｅ彂": "Agency Payroll",
    "鎵归噺杞处": "Bulk Transfer",
    "鎵归噺鎵ｆ": "Bulk Debit",
    "鎵瑰鐞?": "Batch Processing",
    "鏀跺Ε鍏ヨ处": "Posted upon Collection",
    "瀹炴椂鍏ヨ处": "Real-time Posting",
    "鏉ヨ处鍏ヨ处": "Incoming Transfer Posted",
    "杞处姹囨": "Transfer Remittance",
    "鏉ヨ处鎻愰啋": "Incoming Transfer Alert",
    "杞瓨": "Rollover Deposit",
    "缁瓨": "Deposit Renewal",
    "缁撴竻": "Settled",
    "瑙ｄ粯": "Payment Release",
    "鎵垮厬": "Acceptance",
    "鎵樻敹": "Collection",
    "鎵樻敹鎵夸粯": "Collection and Acceptance",
    "鍚屽煄浜ゆ崲": "Local Clearing",
    "寰€鏉ユ": "Intercompany Funds",
    "鎸傝处": "Suspense Entry",
    "寰呮竻绠?": "Pending Clearing",
    "寰呭叆璐?": "Pending Posting",
    "璋冭处": "Account Adjustment",
    "琛ヨ": "Supplementary Entry",
    "鏇存": "Correction",
    "绾㈠瓧鍐查攢": "Red Reversal",
    "钃濆瓧鏇存": "Blue Correction",
    "鎵嬬画璐瑰噺鍏?": "Service Fee Waiver",
    "鍒╂伅绋?": "Interest Tax",
    "鏈伅杞瓨": "Principal and Interest Rollover",
    "鑷姩杞瓨": "Automatic Rollover",
}


EXTENDED_BANK_TERMS: Dict[str, str] = {
    "鍒嗘湡浠樻": "Installment Payment",
    "棰勬巿鏉?": "Pre-authorization",
    "棰勬巿鏉冩挙閿€": "Pre-authorization Cancellation",
    "棰勬巿鏉冨畬鎴?": "Pre-authorization Complete",
    "鎸傚け": "Report Loss",
    "瑙ｆ寕": "Unfreeze Account",
    "鍐荤粨": "Freeze",
    "瑙ｅ喕": "Unfreeze",
    "鎸傚け璐?": "Report Loss Fee",
    "琛ュ崱璐?": "Card Replacement Fee",
    "杞处鎵嬬画璐?": "Transfer Fee",
    "姹囧垝璐?": "Remittance Fee",
    "鏌ヨ璐?": "Inquiry Fee",
    "鎵撳嵃璐?": "Printing Fee",
    "姘寸數璐?": "Utility Bill",
    "鐓ゆ皵璐?": "Gas Bill",
    "鐗╀笟璐?": "Property Fee",
    "瀛﹁垂": "Tuition Fee",
    "淇濋櫓璐?": "Insurance Premium",
    "鍖荤枟璐?": "Medical Fee",
    "鎸傚彿璐?": "Registration Fee",
    "鏀粯瀹?": "Alipay",
    "寰俊鏀粯": "WeChat Pay",
    "璐粯閫?": "Tenpay",
    "閾惰仈": "UnionPay",
    "浜戦棯浠?": "UnionPay QuickPass",
    "娣樺疂": "Taobao",
    "澶╃尗": "Tmall",
    "浜笢": "JD.com",
    "鎷煎澶?": "Pinduoduo",
    "鍞搧浼?": "Vipshop",
    "缇庡洟": "Meituan",
    "楗夸簡涔?": "Eleme",
    "鐩掗┈": "Freshippo",
    "婊存淮鍑鸿": "Didi",
    "婊存淮": "Didi",
    "鏇规搷鍑鸿": "Caocao",
    "棣栨苯绾﹁溅": "First Taxi",
    "绁炲窞涓撹溅": "Shenzhou",
    "鍦伴搧": "Metro",
    "鍏氦": "Bus",
    "鍑虹杞?": "Taxi",
    "鑵捐瑙嗛": "Tencent Video",
    "鐖卞鑹?": "iQiyi",
    "浼橀叿": "Youku",
    "鑺掓灉TV": "Mango TV",
    "鍝斿摡鍝斿摡": "Bilibili",
    "鎶栭煶": "Douyin",
    "蹇墜": "Kuaishou",
    "缃戞槗浜戦煶涔?": "NetEase Cloud Music",
    "QQ闊充箰": "QQ Music",
    "閰风嫍闊充箰": "Kugou Music",
    "鑽簵": "Pharmacy",
    "鑽埧": "Pharmacy",
    "鍖婚櫌": "Hospital",
    "璇婃墍": "Clinic",
    "绀惧尯鍗敓鏈嶅姟涓績": "Community Health Center",
    "瀛︽牎": "School",
    "澶у": "University",
    "鍩硅鏈烘瀯": "Training Institution",
    "鏁欒偛": "Education",
    "绋庡姟灞€": "Tax Bureau",
    "鍏畨灞€": "Public Security Bureau",
    "姘戞斂灞€": "Civil Affairs Bureau",
    "宸ュ晢灞€": "Industry and Commerce Bureau",
    "鏈夐檺鍏徃": "Limited",
    "鑲′唤鏈夐檺鍏徃": "Co., Ltd.",
    "鏈夐檺璐ｄ换鍏徃": "Limited Liability Company",
    "闆嗗洟": "Group",
    "鍏徃": "Company",
    "浼佷笟": "Enterprise",
    "鍖椾含": "Beijing",
    "涓婃捣": "Shanghai",
    "娣卞湷": "Shenzhen",
    "骞垮窞": "Guangzhou",
    "鏉窞": "Hangzhou",
    "鎴愰兘": "Chengdu",
    "閲嶅簡": "Chongqing",
    "姝︽眽": "Wuhan",
    "瑗垮畨": "Xi'an",
    "鍗椾含": "Nanjing",
    "鑻忓窞": "Suzhou",
    "澶╂触": "Tianjin",
    "闀挎矙": "Changsha",
    "閮戝窞": "Zhengzhou",
    "娴庡崡": "Jinan",
    "闈掑矝": "Qingdao",
    "澶ц繛": "Dalian",
    "娌堥槼": "Shenyang",
    "鍝堝皵婊?": "Harbin",
    "闀挎槬": "Changchun",
    "绂忓窞": "Fuzhou",
    "鍘﹂棬": "Xiamen",
    "鍗楁槍": "Nanchang",
    "鍚堣偉": "Hefei",
    "鏄嗘槑": "Kunming",
    "璐甸槼": "Guiyang",
    "澶師": "Taiyuan",
    "鐭冲搴?": "Shijiazhuang",
    "鍏板窞": "Lanzhou",
    "涔岄瞾鏈ㄩ綈": "Urumqi",
    "鍛煎拰娴╃壒": "Hohhot",
    "鍗楀畞": "Nanning",
    "娴峰彛": "Haikou",
}
