"""Compatibility aliases for historically garbled PDF-extracted text."""

from __future__ import annotations

from typing import Dict


GARBLED_BANK_TERMS: Dict[str, str] = {
    "宸ヨ祫": "Salary",
    "娑堣垂": "Consumption",
    "杞处": "Transfer",
    "鏀粯瀹?": "Alipay",
    "寰俊鏀粯": "WeChat Pay",
    "閿涘牏鈹栭敍?": "",
    "(缁?": "",
    "缁?": "",
    "閺?": "",
    "閹芥顩?": "Description",
    "閸︽澘灏?": "Region",
    "鐎佃鏌熼幋宄版倳": "Counterparty Name",
    "鐎佃鏌熺拹锕€褰?": "Counterparty Account",
    "濞撶娀浜?": "Channel",
    "閸屻劎顫?": "Savings Type",
    "鐢胶顫?": "Currency",
    "闁界偞鐪?": "Cash/Transfer",
    "閺€璺哄弳": "Income",
    "閺€顖氬毉": "Expenditure",
    "閺€璺哄弳/閺€顖氬毉": "Income/Expenditure",
    "閺€璺哄弳/閺€顖氬毉闁叉垿顤?": "Income/Expenditure Amount",
    "鏉烆剝澶?": "Transfer",
    "鏉烆剙鍙?": "Transfer In",
    "鏉烆剙鍤?": "Transfer Out",
    "閺夈儴澶?": "Incoming Transfer",
    "瀵扳偓鐠?": "Outgoing Transfer",
    "濮瑰洤鍙?": "Incoming Remittance",
    "濮瑰洤鍤?": "Outgoing Remittance",
    "濞戝牐鍨?": "Consumption",
    "闁偓濞?": "Refund",
    "鏉╂ɑ顑?": "Repayment",
    "鐠愰攱顑欐潻妯活儥": "Loan Repayment",
    "娣囷紕鏁ら崡陇绻曞▎?": "Credit Card Repayment",
    "瀹搞儴绁?": "Salary",
    "娴狅絽褰傚銉ㄧカ": "Payroll",
    "婵傛牠鍣?": "Bonus",
    "閸掆晜浼?": "Interest",
    "缂佹挻浼?": "Interest Settlement",
    "閹靛鐢荤拹?": "Service Fee",
    "瀹搞儲婀扮拹?": "Card Production Fee",
    "楠炵鍨?": "Annual Fee",
    "鐠愶附鍩涚粻锛勬倞鐠?": "Account Management Fee",
    "閹绘劗骞?": "Withdrawal",
    "閻滀即鍣剧€涙ê鍙?": "Cash Deposit",
    "閻滀即鍣鹃弨顖氬絿": "Cash Withdrawal",
    "閸忓懎鈧?": "Top Up",
    "閹碉絾顑?": "Debit",
    "娴狅絾澧?": "Auto Debit",
    "娴狅絾鏁?": "Collection",
    "韫囶偅宓庨弨顖欑帛": "Quick Payment",
    "缂冩垳绗傞弨顖欑帛": "Online Payment",
    "閺冪姴宕遍弨顖欑帛": "Cardless Payment",
    "閹殿偆鐖滈弨顖欑帛": "QR Code Payment",
    "閹靛婧€闁炬儼顢?": "Mobile Banking",
    "缂冩垳绗傞柧鎯邦攽": "Online Banking",
    "閼奉亜濮紒鍫㈩伂": "Self-Service Terminal",
    "閺屾粌褰?": "Counter",
    "閻滀即鍣?": "Cash",
    "閻滅増鐪?": "Remittance",
    "閻滀即鎸?": "Cash",
    "闁?": "Cash",
    "濮?": "Remittance",
    "濞茬粯婀?": "Demand Deposit",
    "鐎规碍婀?": "Time Deposit",
    "娴滅儤鐨敮?": "CNY",
    "缂囧骸鍘?": "USD",
    "濞喲冨帗": "EUR",
    "閼婚亶鏅?": "GBP",
    "濞擃垰绔?": "HKD",
    "閺冦儱鍘?": "JPY",
    "濠㈠啿鍘?": "AUD",
    "閸旂姴鍘?": "CAD",
    "閺傛澘濮為崸鈥冲帗": "SGD",
}


GARBLED_EXACT_TERM_OVERRIDES: Dict[str, str] = {
    "缂冩垿鎽遍崷銊у殠閿涘牆瀵虫禍顒婄礆缁夋垶濡ч張澶愭閸忣剙寰?": "NetBank Online (Beijing) Technology Co Ltd",
    "缂冩垿鎽遍崷銊у殠(閸栨ぞ鍚?缁夋垶濡ч張澶愭閸忣剙寰?": "NetBank Online (Beijing) Technology Co Ltd",
    "閺€顖欑帛鐎规繐绱欐稉顓炴禇閿涘缍夌紒婊勫Η閺堫垱婀侀梽鎰彆閸?": "Alipay (China) Network Technology Co Ltd",
    "閺€顖欑帛鐎?娑擃厼娴?缂冩垹绮堕幎鈧張顖涙箒闂勬劕鍙曢崣?": "Alipay (China) Network Technology Co Ltd",
    "閸忓鑳洪獮鍨簚閸︿即鎼閸戝搫褰涙笟鍨焺鐡掑懎绔?": "Guanggu Plaza Metro C Exit Convenience Store",
    "濮濓附鐪界敮鍌欑濠€鏍ㄦ煀閹垛偓閺堫垰绱戦崣鎴濆隘閻滃鈹撻弲鎾瑰閸楁顦垫顔肩暗": "Wang Ting Xiaofu Nan Restaurant, East Lake Hi-Tech Development Zone, Wuhan",
    "娴滎兛绗㈤惂鑺ユ蒋閸欏﹪鍣鹃弶鈥茬瑹閸旓紕缍夐柧璺洪挬閸?": "JD Baitiao and Jintiao Online Banking Platform",
    "娴滎兛绗㈤崯鍡楃厔娑撴艾濮?": "JD Mall Services",
    "濮诡亝娅?": "Wang Jing",
    "缂囧骸娲熼獮鍐插酱閸熷棙鍩?": "Meituan Platform Merchant",
    "鐠愵澀绮柅?": "Tenpay",
    "濮濓附鐪芥稉顓犳娓氬灝鍩勬惔?": "Wuhan Zhongbai Convenience Store",
    "濞ｅ崬婀风敮鍌濆偍娴犳﹢鈧碍鏁禒妯碱潠閹垛偓閺堝妾洪崗顒€寰?": "Shenzhen Tenpay Payment Technology Co Ltd",
}
